GET http://localhost:3000/api/clientes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMywiZXhwaXJhdGlvbiI6MTYzMTYzMzMwOSwiaWF0IjoxNjIzNjg0NTA5fQ.v7I7l2bRl8uEUqHCzVjS47HVzQchhNEKcg-Obi0OQW4

###
GET http://localhost:3000/api/profesores/detalle/28
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMywiZXhwaXJhdGlvbiI6MTYzMTYzMzMwOSwiaWF0IjoxNjIzNjg0NTA5fQ.v7I7l2bRl8uEUqHCzVjS47HVzQchhNEKcg-Obi0OQW4


###
GET http://localhost:3000/api/profesores/provincia/madrid
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMywiZXhwaXJhdGlvbiI6MTYzMTYzMzMwOSwiaWF0IjoxNjIzNjg0NTA5fQ.v7I7l2bRl8uEUqHCzVjS47HVzQchhNEKcg-Obi0OQW4


###
GET http://localhost:3000/api/profesores
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyNywiZXhwaXJhdGlvbiI6MTYzMjIzNDcwMywiaWF0IjoxNjI0Mjg1OTAzfQ.BEwM9QQJNmF70VaBrhFH6s-nHp3n6sRvCDIS7bhR1t0


###
GET http://localhost:3000/api/profesores/price/?min=8&max=16
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMywiZXhwaXJhdGlvbiI6MTYzMTYzMzMwOSwiaWF0IjoxNjIzNjg0NTA5fQ.v7I7l2bRl8uEUqHCzVjS47HVzQchhNEKcg-Obi0OQW4


###
GET http://localhost:3000/api/clientes/user/3


### REGISTRO DE PROFESOR
POST http://localhost:3000/api/profesores/create
Content-Type: application/json

{
    "experiencia": 3, 
    "precio": 8, 
    "material_propio": 1, 
    "niveles": 3, 
    "desplazamiento":1, 
    "rango_desplazamiento":30,
    "fk_usuario": 14 
   
}

### REGISTRO DE USUARIO
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
    "username": "Jualolo10", 
    "nombre": "Fernando", 
    "apellidos":"Alonso Ruiz", 
    "email":"definitivo22@gmail.com", 
    "telefono": 673429509,
    "password":"1234"
}

### LOGIN DE USUARIO
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "definitivo@gmail.com",
    "password": "1234"
}

###
PUT http://localhost:3000/api/clientes/update
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMywiZXhwaXJhdGlvbiI6MTYzMTYzMzMwOSwiaWF0IjoxNjIzNjg0NTA5fQ.v7I7l2bRl8uEUqHCzVjS47HVzQchhNEKcg-Obi0OQW4

Content-Type: application/json

{
    "nombre": "Ferreterias Luso",
    "nivel": "3"
}


###
PUT http://localhost:3000/api/clientes/upimg
Content-Type: application/json

{
    "img_cliente": "soeosoeososos"
}

###
GET http://localhost:3000/api/profesores/instalations/1


###
GET http://localhost:3000/api/profesores/level/3

###
PUT http://localhost:3000/api/clientes/changepw
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyNywiZXhwaXJhdGlvbiI6MTYzMjIzNDcwMywiaWF0IjoxNjI0Mjg1OTAzfQ.BEwM9QQJNmF70VaBrhFH6s-nHp3n6sRvCDIS7bhR1t0

Content-Type: application/json

{
    "password1": "12345",
    "id": 2
}
